---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/contacts":
    post:
      summary: Creates a contact
      tags:
      - Contacts
      parameters: []
      responses:
        '201':
          description: contact created
        '422':
          description: invalid request
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                birthdate:
                  type: string
                  format: date
                imagem:
                  type: file
              required:
              - name
              - email
    get:
      summary: Retrieves a list of contacts
      tags:
      - Contacts
      responses:
        '200':
          description: list of contacts
  "/contacts/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Retrieves a contact
      tags:
      - Contacts
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: contact found
        '404':
          description: contact not found
    put:
      summary: Updates a contact
      tags:
      - Contacts
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: contact updated
        '422':
          description: invalid request
        '404':
          description: contact not found
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                birthdate:
                  type: string
                  format: date
                imagem:
                  type: file
    delete:
      summary: Deletes a contact
      tags:
      - Contacts
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: contact deleted
        '404':
          description: contact not found
  "/kinds":
    post:
      summary: Creates a kind
      tags:
      - Kinds
      parameters: []
      responses:
        '201':
          description: kind created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
              required:
              - description
    get:
      summary: Retrieves a list of kinds
      tags:
      - Kinds
      responses:
        '200':
          description: list of kinds
  "/kinds/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Retrieves a kind
      tags:
      - Kinds
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: kind found
        '404':
          description: kind not found
    put:
      summary: Updates a kind
      tags:
      - Kinds
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: kind updated
        '422':
          description: invalid request
        '404':
          description: kind not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
    delete:
      summary: Deletes a kind
      tags:
      - Kinds
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: kind deleted
        '404':
          description: kind not found
  "/phones":
    post:
      summary: Creates a phone
      tags:
      - Phones
      parameters: []
      responses:
        '201':
          description: phone created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                number:
                  type: string
                contact_id:
                  type: integer
              required:
              - number
              - contact_id
    get:
      summary: Retrieves a list of phones
      tags:
      - Phones
      responses:
        '200':
          description: list of phones
  "/phones/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Retrieves a phone
      tags:
      - Phones
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: phone found
        '404':
          description: phone not found
    put:
      summary: Updates a phone
      tags:
      - Phones
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: phone updated
        '422':
          description: invalid request
        '404':
          description: phone not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                number:
                  type: string
                contact_id:
                  type: integer
    delete:
      summary: Deletes a phone
      tags:
      - Phones
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: phone deleted
        '404':
          description: phone not found
