---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/contacts":
    get:
      summary: list contacts
      responses:
        '200':
          description: successful
    post:
      summary: create contact
      responses:
        '200':
          description: successful
  "/contacts/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show contact
      responses:
        '200':
          description: successful
    patch:
      summary: update contact
      responses:
        '200':
          description: successful
    put:
      summary: update contact
      responses:
        '200':
          description: successful
    delete:
      summary: delete contact
      responses:
        '200':
          description: successful
  "/kinds":
    get:
      summary: list kinds
      tags:
      - Kinds
      responses:
        '200':
          description: successful
    post:
      summary: create a kind
      tags:
      - Kinds
      parameters: []
      responses:
        '201':
          description: kind created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
              required:
              - description
  "/kinds/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show kind
      tags:
      - Kinds
      responses:
        '200':
          description: successful
    patch:
      summary: update kind
      tags:
      - Kinds
      responses:
        '200':
          description: successful
    put:
      summary: update kind
      tags:
      - Kinds
      responses:
        '200':
          description: successful
    delete:
      summary: delete kind
      tags:
      - Kinds
      responses:
        '200':
          description: successful
